### ISSUE TITLE
vlc-3.0.0 (2018/02/10) - attempting to start only produces POPUPLOG.OS2 error

### ISSUE THREAD

**Issue by dspiatkowski** [komh/vlc-os2#11]
Upgraded from vlc-2.2.8 (2017/12/17), now upon startup (either CLI or through WPS object) only the following error appears in the POPUPLOG.OS2:

------------------------------------------------------------
03-16-2018  16:08:25  SYS2070  PID 0062  TID 0001  Slot 00db
G:\APPS\MULTIMEDIA\VLC2\USR\LOCAL\BIN\VLC.EXE
ACCESS_B->VLCCORE._stream_Control
127
------------------------------------------------------------
03-16-2018  16:08:25  SYS2070  PID 0062  TID 0001  Slot 00db
G:\APPS\MULTIMEDIA\VLC2\USR\LOCAL\BIN\VLC.EXE
ACCESS_B->VLCCORE._stream_Control
127
------------------------------------------------------------

Not a mistake, the same error is repeated twice in the log. This happens each time I attempt to start VLC.

The machine is: OS/2 Warp4 CP2, SMP, ACPI 2.23.08, running 14.201_SMP kernel.

VIDEO: AN SNAP driver
AUDIO: UniAudio (see details at end of ticket)

Attempting to capture a log using 'vlc.exe -vvv --file-logging media-filename > vlc-err.txt 2>&1' produces a zero length file.

UniAudio Details
===========
----- Output of: bldlevel.exe G:\MMOS2\UNIAUD32.SYS ----------------------------
Build Level Display Facility Version 6.12.675 Sep 25 2001
(C) Copyright IBM Corporation 1993-2001
Signature:       @#Netlabs:1.09.26#@##1## 23 Sep 2013 09:41:51     DAZAR1    :1.0.21:::26::@@Universal Audio Driver for OS/2 and eComStation (KEE)
Vendor:          Netlabs
Revision:        1.09.26
Date/Time:       23 Sep 2013 09:41:51   
Build Machine:   DAZAR1    
ASD Feature ID:  1.0.21
File Version:    1.9.26
Description:     Universal Audio Driver for OS/2 and eComStation (KEE)
----- Output of: bldlevel.exe G:\MMOS2\UNIAUD16.SYS ----------------------------
Build Level Display Facility Version 6.12.675 Sep 25 2001
(C) Copyright IBM Corporation 1993-2001
Signature:       @#Netlabs:1.09.06#@##1## 19 Sep 2013 16:05:58     DAZAR1    ::::06::@@Universal Audio MMPM/2 Driver for eComStation
Vendor:          Netlabs
Revision:        1.09.06
Date/Time:       19 Sep 2013 16:05:58   
Build Machine:   DAZAR1    
File Version:    1.9.6
Description:     Universal Audio MMPM/2 Driver for eComStation
----- Output of: unimix.exe -card ----------------------------------------------
Command line mixer for UNIAUD32. Version 1.1
Detected UNIAUD version 1.09.26
Detected 2 audio adapter(s)
Card info for adapter 0:
  num: 0
  id: SB
  driver: HDA-Intel
  name: HDA ATI SB
  longname: HDA ATI SB at 0xfe8f4000 irq 16
  mixer: Realtek ALC889
  componenets: HDA:10ec0889,14627576,00100004

**Comment by komh** [comment]
access_b.dll is not a valid dll for vlc 3.0.0. Maybe, did you overwrite vlc 3.0.0 to vlc 2.2.8 ? Remove or rename vlc 2.2.8 directory. And unzip vlc 3.0.0, then retry, please...

**Comment by dspiatkowski** [comment]
Hi Ko!

Indeed, you are absolutely right.

I did overwrite the existing install because I start VLC from a vlc.cmd and  
I did not want WPS to re-point to a Trash can, etc, etc...was trying to  
avoid some issues actually.

I had re-done this now, all works fine here. Thank you!

  -Dariusz

**Comment by komh** [comment]
Good to know that. ^^
