### ISSUE TITLE
screen flashes and resizes continuously - sound but no video

### ISSUE THREAD

**Issue by a90909** [komh/vlc-os2#12]
When playing a *
[vlc-err.txt](https://github.com/komh/vlc-os2/files/1876467/vlc-err.txt)
[vlc-log.txt](https://github.com/komh/vlc-os2/files/1876469/vlc-log.txt)

.mp4 or *.mpg file the VLC  screen resizes larger, then back to smaller, then larger, etc. This happens very quickly and continously until the file is done. No video shows but sound does play.

vlc v 3.0.1. ArcaOS v 5.0.2.  AMD processor (FX4350), SMP, uniaud32.sys, ArcaNoae SNAP build 506, version 3.02

Version 1.1.9 plays the video correctly and the screen doesn't continously resize, but has no sound.

**Comment by komh** [comment]
In the log, kva failed repeatedly. So, I think, continous resizing is trying open video window with kva and closing video window because of kva failure.

Please provide the testcase file failing to play.

**Comment by komh** [comment]
KVA(K Video Accelerator) is the video output library used by VLC. In the log, KVA setup failed repeatedly.

I'm also not sure that your mp4 file has problem or not. So I want to confirm it.

For github, you can upload them by zipping or just append .zip.

**Comment by a90909** [comment]
Here is the file
[clip.zip](https://github.com/komh/vlc-os2/files/1884258/clip.zip)

**Comment by a90909** [comment]
More information:

VLC works in VMAN and DIVE modes. I get the strange behavior in all the other modes.

In VMAN and DIVE the video plays a separate window which occupies a whole screen. The regular VLC window is behind the one playing the video. If I move the regular VLC window out from behind the window playing the video I can use the menu on the regular VLC window. (I have dual monitors so I   can move the regular VLC window from behind the window playing the video on one monitor to the other monitor.)

The video card is ATI Radeon X600 series and it is accelerated.

**Comment by a90909** [comment]
BTW - thanks for your help.

**Comment by komh** [comment]
Ok, good.

It was because your video driver did not support SNAP mode. I would recommend to use AUTO mode intead of setting to other specific modes such as VMAN or DIVE. Then KVA will selecte the available modes automatically. Nevertheless, if you encounter the problem, then try to select a mode manually.

In case of a playing window appearance, you seemed to uncheck [Integrate video in interface] of [Interface] tab of [Preferences]. Check it again, please.
