### ISSUE TITLE
Quick test of VLC 3.0.7.1: 'View' menu is doubled, then tripled, and keeps growing

### ISSUE THREAD

**Issue by mrwarper** [komh/vlc-os2#16]
Wanted to have a go at the newest VLC. Contents of 'View' menu are shown twice the first time the mouse hovers it. Each time I move the mouse pointer to another menu and back, 'View' gets an additional copy of its whole contents appended to it. I took some (partial) captures:

[Sorry for the many edits: my only 'up-to-date' FireFox lives on a SmartPhone with the multilingual corrector from hell]

**Comment by mrwarper** [comment]
Apparently I can't upload the screenshots :-?

Anyway, this is an outdated MCP2 system cobbled together. If this bug can't be reproduced on your side, that's fine -- I assume my QT4 installation may have some quirks.

**Comment by komh** [comment]
Hi/2.

I could reproduce here, and I've fixed. 

BTW, this seems to be a bug of Qt4 for OS/2 because this problem does not appear on other platforms such as Windows.

Please test fixed version.

[qt_plugin_test.zip](https://github.com/komh/vlc-os2/files/3377047/qt_plugin_test.zip)

Just overwrites with unzipping to your vlc2 directory.

**Comment by mrwarper** [comment]
Hi/2

On 19/07/10 12:35, KO Myung-Hun wrote:
> Hi/2.
>
> I could reproduce here, and I've fixed.
>
> BTW, this seems to be a bug of Qt4 for OS/2 because this problem does not
> appear on other platforms such as Windows.

OK, all menus worked except that one so I thought 1.VLC-port, 2.My system, 
3.QT4-os2 0:-O

> Please test fixed version.

Big file, but all menus seem to work now, thanks a million ^^

Now I need to find time to test (watch movies ;)

Cheers,
AFD.

**Comment by komh** [comment]
Thanks for your report!
