### ISSUE TITLE
Vlc short time freezing, when playing matroska video (.mkv)

### ISSUE THREAD

**Issue by cultorhei** [komh/vlc-os2#20]
When watching a matroska container-packed video (Ivalo_S01E06.mkv) with subtitles, playback stops for a few seconds at approximately 2-15 minute intervals. Sometimes just the picture stops, the sound continues.

I doubt it has to do with subtitles rendering, because every now and then the subtitles are mixed up.

For example, 'Maistuuko se tältädeev ltä?' It should be 'Maistuuko se tältä vedeltä? ('Does it taste like this water?')
or 'En tunnetnäh ä' should be 'En tunne häntä.' ('I don't know him.')

 I've also seen 'aM rcus.' when it should have been 'Marcus.'

Same Ivalo_S01E06.mp4 with subtitle file Ivalo_S01E06.srt plays fine.

https://www.imdb.com/title/tt7906110/?ref_=ttep_ep6

[ffprobe_mkv.txt](https://github.com/komh/vlc-os2/files/6018213/ffprobe_mkv.txt)
[ffprobe_mp4.txt](https://github.com/komh/vlc-os2/files/6018214/ffprobe_mp4.txt)

**Comment by komh** [comment]
Hi/2.

First, could you test on other platforms such as Windows ?

Second, how can I get those files ?

Thanks for your reports!

**Comment by cultorhei** [comment]
I tested Samsung laptop (Win7) and VLC 3.0.12. Plays well. I also tested the Xubuntu 18.04.5 LTS on my computer, which is identical to my ArcaOS 5.04 (Dell Optiplex 960). Xubuntu has VLC 3.0.8, played well.

I've saved videos from Yle Areena https://areena.yle.fi/1-4231749 with yle-dl  program https://aajanki.github.io/yle-dl/index-en.html. The video address  it is probably limited to the country and does not work outside Finland. I can load video to other server and send the download address by email. Is the email address on your list active? I have also gmail address in my address book.

Thanks for your work compiling programs for OS/2!

**Comment by komh** [comment]
Please send the link  to me(email on this list).

**Comment by komh** [comment]
Can I know the time when those subtitles are shown ?

**Comment by cultorhei** [comment]
First finnish subs (Track 1) are in 02:41. Errors occur at random intervals. When you are in a different country, you may need to select the subtitles and default character set used by Vlc.  Subs are utf-8 character set.

**Comment by komh** [comment]
I've watch the whole movie with Track1 - [Finnish] subtitle continuously, but I could not encounter any freezing.

1. For freezing, how about disabling subtitle ? Does freezing still occur ?
2. If you can tell me the place where subtitle texts are shown wrongly, I'll appreciate very much.

**Comment by cultorhei** [comment]
I have 2 screenshots. 
Subtitle 29 
00:05:50,920 --> 00:05:54,240 
Maistuuko se tältä vedeltä?
- Joo, paskaa on.

![vlcs_mkv01](https://user-images.githubusercontent.com/79097042/108850524-22b5bf00-75ec-11eb-9779-79835f7889ad.jpg)

Subtitle 79
00:12:19,600 --> 00:12:23,240 
Entä tämä mies?
- En tunne häntä.
![vlc_mkv02](https://user-images.githubusercontent.com/79097042/108851029-aa033280-75ec-11eb-9d14-f96a51cd983b.jpg)

**Comment by komh** [comment]
Here is my screenshot:

![png1](https://user-images.githubusercontent.com/1104659/108856157-1b62d580-762d-11eb-9331-25f3f27f2e61.png)

![png2](https://user-images.githubusercontent.com/1104659/108856186-2158b680-762d-11eb-82e0-a42aafed8e54.png)

**Comment by cultorhei** [comment]
Your screenshots are correct. I watched through the video without subtitles, no freezing. I looked other video a little, then closed VLC. Started again Ivalo_S01E06.mkv and first freezing at 00:33, crash about 05:01. Next attempt at crashed same position. After some time new attempt ended crash at 21:40. I will look more tomorrow and also VLC preferences.

**Comment by komh** [comment]
Did you do clean-install ? And I would suggest do clean-install and remove $HOME/vlcrc and $HOME/.config/vlc/* for fresh test.

**Comment by cultorhei** [comment]
I removed $HOME/vlcrc and $HOME/.config/vlc/*. Video KVA defaults Auto and then SNAP is in use. It would be the best option but in my system it will lead to complete freezing sooner or later. Must reboot with Ctrl - Alt - Del. So I chose VMAN instead of DIVE I used  earlier. With VMAN I didn't see freezing but subtitles were mixed sometimes.
![vlc_mkv11](https://user-images.githubusercontent.com/79097042/109037620-97175d80-76d3-11eb-9351-6e204b0ebab7.jpg)
Should be - En tunne häntä.

**Comment by komh** [comment]
Then, try first without marking so, please.

**Comment by cultorhei** [comment]
Without marking all dll high VLC crashed at about 2:40 on the first attempt and the subtitles mix in much the same way. 006C_12.TRP included.

 No freezing when VMAN is enabled. Most .trp files show crash on G:\VLC2\USR\LOCAL\LIB\VLC\PLUGINS\TEXT_RENDERER\FREETYPE.DLL
[006C_12_TRP.zip](https://github.com/komh/vlc-os2/files/6045317/006C_12_TRP.zip)

**Comment by komh** [comment]
1. Freezing occurs only on DIVE ? 
2. corruption of characters occur and crashes on both VMAN and DIVE ?

It's strange that DIVE with SNAP driver has a problem. It has been known that DIVE with Panorama driver is not happy.

BTW, You can use VMAN mode by default with ```SET KVA_AUTOMODE=VMAN``` for all the apps using the latest libkva.

Here is the debug version of freetype.dll. Replace your ```G:\VLC2\USR\LOCAL\LIB\VLC\PLUGINS\TEXT_RENDERER\FREETYPE.DLL``` with this: [freetype.zip](https://github.com/komh/vlc-os2/files/6047589/freetype.zip) This is useful for .TRP.

And please provide vlc-err.txt and vlc-log.txt.

**Comment by komh** [comment]
I've updated some codes of unicode conversion. Try this:

[freetype.zip](https://github.com/komh/vlc-os2/files/6048457/freetype.zip)

**Comment by cultorhei** [comment]
1. Yes
2. Yes

With first debug version first text mixing appeared at 04:22. Second debug freetype.dll looks promising. No text mixing so far. I'll look next episode with VLC and tell more in a few days.

[vlc-err.txt](https://github.com/komh/vlc-os2/files/6048915/vlc-err.txt)
[vlc-log.txt](https://github.com/komh/vlc-os2/files/6048917/vlc-log.txt)

**Comment by komh** [comment]
1: Then, use VMAN, please.
2: Good. I'm looking forward to see the good result. ^^

**Comment by cultorhei** [comment]
I put the SET KVA_AUTOMODE = VMAN line in config.sys. With the latest freetype.dll video playback has worked well. I just watched episode 8 of the Ivalo series. The subtitles were displayed correctly, and no jerking in playback.

The other day, I organized my video library and watched many videos for a few minutes to see what they are. Vlc worked flawlessly.

Thank you for your work.
Best regards 
Heikki

**Comment by komh** [comment]
Ok, thanks!

**Comment by cultorhei** [comment]
For your information. I've marked all dll files of VLC to load into high memory.

**Comment by komh** [comment]
Good to know that!
