### ISSUE TITLE
VLC 3.0.12 - using SNAP drivers the Menu Bar selections are see-through

### ISSUE THREAD

**Issue by dspiatkowski** [komh/vlc-os2#21]
This was the case in the prior version as well (3.0.10), however given that using SNAP (or the KVA Auto mode) produces better quality output (captions are very smooth, etc.) I am using that configuration.

Alright, so what happens?

When SNAP is activated, selecting any menu from the Tool Bar open up the drop-down menu, however the menu items actually appear to be see-through, meaning the outlines are there but depending on the contents of the video background they either show, or only white outlines show.

I'm going to attach two screen captures:
1) actual PMView capture of real playback where the capture itself does not show the issue, this is despite the fact that the issue is actually occuring
2) cell phone capture of this very same section of the screen showing the actual result

**Comment by dspiatkowski** [comment]
screen captures

**Comment by dspiatkowski** [comment]
umm...did the screen capture attach actually work? I do not see them in the previous update, please let me know if I should re-do them?

**Comment by komh** [comment]
I could not see the screen captures at all.

This problem occurs while playing ? It's strange that tool-bar and video window parts have not been updated during 3.0.x releases. 

One thing considerable is color-key. If color of text is same as color-key of VLC video window, then video contents will show through texts. VLC uses 0x0F0F0F(RGB) color-key. In this case, check your text color of Qt4.

**Comment by dspiatkowski** [comment]
Hmm...looks like a github and my FF issue...so here is another take:

1) http://darcio.no-ip.org/os2/VLC%20-%20screen_capture_OK.png

2) http://darcio.no-ip.org/os2/VLC%20-%20screen_capture_NOT-OK.png

Yes, the problem occurs only when playing back the video, otherwise the rendering is fine.

Hmm....'color-key', not sure how to set this, but I'm happy to run a little bit of research into this, appreciate the hint!

**Comment by komh** [comment]
If a color of video content changes, then a color of text also changes according to a color of video content ?

**Comment by dspiatkowski** [comment]
Yes, when the video content changes the Menu entries also change.

So here is what I did, I took a single additional screenshot that shows how the Menu entries render differently given the video colours. You will see that when the video background is dark blue the menu is fine, but when it's white the menu entries exhibit the problem, see the following URL:

1) http://darcio.no-ip.org/os2/VLC%20-%20screen_capture_NOT-OK_2.png

The second one is a video recording of when I actually move the Settings window around. The field labels there show the same behaviour.

2) darcio.no-ip.org/os2/VLC - screen_capture_video1.mp4

**Comment by komh** [comment]
You uploaded .mp4 file ? I could not see it.

And if color-key was a problem, all the text should be affected. But it's not. Anyway I would want to see .mp4 file.

**Comment by dspiatkowski** [comment]
Nah, sorry I only included the link to the MP4, just like all the other links to the photos I'm hosting on my private web server. However, that link was missing the "https://" at the front so the Github update didn't make it into the clickable link.

Alright, here it is again, this time fully qualified link: http://darcio.no-ip.org/os2/VLC - screen_capture_video1.mp4

**Comment by dspiatkowski** [comment]
Wow...OK, this Github issue tracker is rather un-cooperative...LOL (probably more likely the old FF we run), sorry the URL above was too long for the line.

Here it is:

http://darcio.no-ip.org/os2/VLC - screen_capture_video1.mp4

**Comment by komh** [comment]
Ok, I've confirmed. Not all back color of text changes. Now, I'm sure this is a color-key problem due to font-aliasing. Font-aliasing blurs around text. Meanwhile, color of 0x0F0F0F is generated.

To test, try this:

[kva.zip](https://github.com/komh/vlc-os2/files/6069901/kva.zip)

Overwrite it to your kva_plug.dll.

**Comment by dspiatkowski** [comment]
Yes, that works and fixes the issue I reported! I tried with both the Menu Bar entries as well as by moving the Settings window around. Both display correctly. Thank you.

**Comment by komh** [comment]
Good! Thanks for your report an test!
