### ISSUE TITLE
Unable to playback MJPG AVI with 2.1.5 Rincewind

### ISSUE THREAD

**Issue by dspiatkowski** [komh/vlc-os2#8]
Attempting to play back a MJPG video generated by Pentax K5 DSLR. Previous versions of VLC had no problem here, as of some more recent version this stopped working. I can not tell when this occured however.

Symptom: AVI is correctely opened, video window is shown but the whole picture remains blank, a small upper left corner shows what appears to be part of video, remainder of the display window shows artifacts, but no actual video plays back. Audio is fine, all appears to function as desired, but simply no video.

I captured the LOG file, will upload next.

**Comment by dspiatkowski** [comment]
Hi KO!

Sorry it took me so long...I am hosting the quick couple seconds of video clip on my local machine, you can reach it at http://darcio.no-ip.org/os2/mjpeg_test.avi

I will update the ticket next.

On my WinXP box, I can play this back using VLC 2.1.5 Rincewind, no problem there. This is not possible on my OS2 box with the very same relase of VLC player.

Thanks again,
-Dariusz

**Comment by dspiatkowski** [comment]
Hi KO!

Sorry it took me so long...I am hosting the quick couple seconds of video clip
on my local machine, you can reach it at
http://darcio.no-ip.org/os2/mjpeg_test.avi

I will update the ticket next.

On my WinXP box, I can play this back using VLC 2.1.5 Rincewind, no problem
there. This is not possible on my OS2 box with the very same relase of VLC
player.

Thanks again,
-Dariusz

**Comment by komh** [comment]
Thanks for your video clip.

And, fortunately, I've found the cause. An codec for MJPG was broken. That codec is avcodec_plugin, which uses FFmpeg. After all, FFmpeg which was used at release time had a problem. Here is a fixed plugin. Save this as **vlc_avcodec_fix.zip** with right-click. And unzip this to your vlc directory with overwriting an old plugin.

![vlc_avcodec_fix zip](https://cloud.githubusercontent.com/assets/1104659/6329028/349299d4-bbb0-11e4-99ee-94552b0cce62.png)

**Comment by dspiatkowski** [comment]
KO!!!

Beautiful...it works...it works!! Thank you so much...I now have my videos back, and that means happy kids and a happy wife.

So I'm curious about something given that you have also done mplayer releases. I have never actually been able to get mplayer to play the mjpeg videos...I use VLC exclusively for that purpose and for watching movies, etc, etc where the more feature loaded aspects of VLC really come in helpfull. But for quick video playback mplayer is still my favourite. Is there a chance that the fix you had done for VLC could be applied to mplayer as well?

I realize it's a different app, but I was always under the impression (maybe mistaken though) that they were both based on the ffmpeg engine...thus the hope.

Thanks,
-Dariusz

**Comment by komh** [comment]
That's good. I've released vlc v2.2.0. Please use it. For MPlayer, the latest version plays MJPEG movies without problems. You can get it at next release of MPlayer.

**Comment by dspiatkowski** [comment]
Hi Ko!

Downloading latest VLC build right now...regarding mplayer though, do you mean that you are working on porting the latest version when you say this "... For MPlayer, the latest version plays MJPEG movies without problems. You can get it at next release of MPlayer..."?

**Comment by komh** [comment]
I'm maintaing MPlayer for OS/2 all the time. ^^

**Comment by dspiatkowski** [comment]
Ko!

Yes, I do know that you maintain the MPlayer port, and since you commented that I can get the MJPEG playback in the next release I'm asking what release that is and whether it is already available for d/l somewhere (I am happy to test), or whether you are currently in the process of porting that version.

The MPLayer version I have here is: 

MPlayer 1.1.1-4.4.6 (C) 2000-2013 MPlayer Team

...and I have not been able to find anything more recent on the usual OS/2 sites....

Thanks!

**Comment by komh** [comment]
Nothing have been released after 1.1.1-4.4.6. And 'release' is an official release by MPlayer team not svn based unofficial release by me.
