### ISSUE TITLE
VLC 2.2.0 can't read DVD

### ISSUE THREAD

**Issue by DavidMcKenna** [komh/vlc-os2#9]
When I try to start any DVD movie with version 2.2.0, I get this message:

Your input can't be opened:
VLC is unable to open the MRL 'dvd:///S:/'. Check the log for details.

 The log says the same thing. I deleted version 2.2.0 and re-installed version 2.1.5r2 and now everything works.

**Comment by komh** [comment]
Thanks for the report. However, it would be better to attach the logs.

**Comment by komh** [comment]
Ok. I can reproduce this here.

I attach the fix. Save it as **vlc-2.2.0-fix1.zip** with mouse-right-button-click,  and unzip it with overwriting to vlc 2.2.0.

![vlc-2 2 0-fix1 zip](https://cloud.githubusercontent.com/assets/1104659/6544764/43f0bd88-c5a2-11e4-9cf5-570a97b168e8.png)

**Comment by DavidMcKenna** [comment]
OK... thanks! That solved the problem.
